= Connections
:imagesdir: ../assets/images

First, we have to define the connections the plugin uses to connect to the Nutanix Prism. A connection consists of
a Username/Password with a Nutanix Prism URL to authenticate against the Prism, and an alias used to reference it. Connections
are saved internally in the Secure Credentials Vault.

You can use REST endpoints and Karaf shell commands to add, validate, and modify connections.

== REST
Some RESTful endpoints are available for basic connection management.

NOTE: The `Content-Type` of the request and response is `application/json`.

[options="header, %autowidth"]
[cols="2,1,3"]
|===
| Resource
| Method
| Description

| `/plugin/tqradro/connections`
| GET
| Returns the list of configured connections.

| `/plugin/tqradro/connections`
| POST
| Adds a new connection.

| `/plugin/tqradro/connections/\{alias}`
| PUT
| Updates a configured connection.

| `/plugin/tqradro/connections/\{alias}`
| DELETE
| Delete a configured connection.

| `/plugin/tqradro/connections/\{alias}`
| GET
| Validates a configured connection.

|===

== Karaf
.Connect to Karaf shell.
[source, console]
----
ssh -p 8101 admin@localhost
----
[source, console]
.List existing connections.
----
admin@opennms()> opennms-tquadro:connection-list --help
DESCRIPTION
        opennms-tqradro:connection-list

	List existing connections

SYNTAX
        opennms-tqradro:connection-list

DETAILS
        List all existing connections to cmdb
----

[source, console]
.Add a connection.
----
admin@opennms()> opennms-tqradro:connection-add --help
DESCRIPTION
        opennms-tqradro:connection-add

	Add a connection

SYNTAX
        opennms-tqradro:connection-add [options] alias url username password length

ARGUMENTS
        alias
                Alias
                (required)
        url
                Prism Url
                (required)
        username
                username
                (required)

        password
                password
                (required)

        length
                Nutanix Prism API object retrivial length defaults to 20
                (defaults to 20)

OPTIONS
        -t, --test
                Dry run mode, test the credentials but do not save them
        --help
                Display this help message
        -f, --force
                Skip validation and save the connection as-is
        -i, --ignore-ssl-certificate-validation
                Ignore ssl certificate validation
DETAILS
        Add a connection to a tqradro prism
----

[source, console]
.Edit an existing connection.
----
admin@opennms()> opennms-tqradro:connection-edit --help
DESCRIPTION
        opennms-tqradro:connection-edit

	Edit a connection

SYNTAX
        opennms-tqradro:connection-edit [options] alias url username password

ARGUMENTS
        alias
                Alias
                (required)
        url
                Prism Url
                (required)
        username
                username
                (required)

        password
                password
                (required)

       length
                Nutanix Prism API object retrivial length defaults to 20
                (defaults to 20)

OPTIONS
        --help
                Display this help message
        -f, --force
                Skip validation and save the connection as-is
        -i, --ignore-ssl-certificate-validation
                Ignore ssl certificate validation
DETAILS
        Edit an existing connection to a tqradro prism
----

[source, console]
.Validate an existing connection.
----
admin@opennms()> opennms-tqradro:connection-validate --help
DESCRIPTION
        opennms-tqradro:connection-validate

	Validate a connection

SYNTAX
        opennms-tqradro:connection-validate alias

ARGUMENTS
        alias
                Alias
                (required)

DETAILS
        Validate an existing connection to a tqradro prism
----

[source, console]
.Delete an existing connection.
----
admin@opennms()> opennms-tqradro:connection-delete --help
DESCRIPTION
        opennms-tqradro:connection-delete

	Delete a connection

SYNTAX
        opennms-tqradro:connection-delete alias

ARGUMENTS
        alias
                Alias
                (required)

DETAILS
        Deletes a connection to a tqradro orchestrator
----

== Examples

The following example adds a connection with the alias `theAlias` and assumes that the Nutanix Prism is reachable by the URL `https://my.prism.net:9440/api/tqradro/v3` and the API-key is `tHiSiS.TheAP1Key`.
```
admin@opennms()> opennms-tqradro:connection-add theAlias https://my.prism.net:9440/ TheUsername ThePassword
```

NOTE: If the connection you can list the associated VM by invoking `opennms-tqradro:list-vms theAlias`.
