= Connections
:imagesdir: ../assets/images

First, we have to define the connections the plugin uses to connect to the TQuadro CMDB. A connection consists of
a Username/Password with a TQuadro CMDB URL to authenticate against the TQuadro Cmdb, and an alias used to reference it. Connections
are saved internally in the Secure Credentials Vault.

You can use REST endpoints and Karaf shell commands to add, validate, and modify connections.

== REST
Some RESTful endpoints are available for basic connection management.

NOTE: The `Content-Type` of the request and response is `application/json`.

[options="header, %autowidth"]
[cols="2,1,3"]
|===
| Resource
| Method
| Description

| `/plugin/tquadro/connections`
| GET
| Returns the list of configured connections.

| `/plugin/tquadro/connections`
| POST
| Adds a new connection.

| `/plugin/tquadro/connections/\{alias}`
| PUT
| Updates a configured connection.

| `/plugin/tquadro/connections/\{alias}`
| DELETE
| Delete a configured connection.

| `/plugin/tquadro/connections/\{alias}`
| GET
| Validates a configured connection.

|===

== Karaf
.Connect to Karaf shell.
[source, console]
----
ssh -p 8101 admin@localhost
----
[source, console]
.List existing connections.
----
admin@opennms()> opennms-tquadro:connection-list --help
DESCRIPTION
        opennms-tquadro:connection-list

	List existing connections

SYNTAX
        opennms-tquadro:connection-list

DETAILS
        List all existing connections to cmdb
----

[source, console]
.Add a connection.
----
admin@opennms()> opennms-tquadro:connection-add --help
DESCRIPTION
        opennms-tquadro:connection-add

	Add a connection

SYNTAX
        opennms-tquadro:connection-add [options] alias url username password

ARGUMENTS
        alias
                Alias
                (required)
        url
                TQuadro Cmdb Url
                (required)
        username
                username
                (required)

        password
                password
                (required)


OPTIONS
        -t, --test
                Dry run mode, test the credentials but do not save them
        --help
                Display this help message
        -f, --force
                Skip validation and save the connection as-is
        -i, --ignore-ssl-certificate-validation
                Ignore ssl certificate validation
DETAILS
        Add a connection to a tquadro cmdb
----

[source, console]
.Edit an existing connection.
----
admin@opennms()> opennms-tquadro:connection-edit --help
DESCRIPTION
        opennms-tquadro:connection-edit

	Edit a connection

SYNTAX
        opennms-tquadro:connection-edit [options] alias url username password

ARGUMENTS
        alias
                Alias
                (required)
        url
                TQuadro Cmdb Url
                (required)
        username
                username
                (required)

        password
                password
                (required)


OPTIONS
        --help
                Display this help message
        -f, --force
                Skip validation and save the connection as-is
        -i, --ignore-ssl-certificate-validation
                Ignore ssl certificate validation
DETAILS
        Edit an existing connection to a tqradro prism
----

[source, console]
.Validate an existing connection.
----
admin@opennms()> opennms-tquadro:connection-validate --help
DESCRIPTION
        opennms-tquadro:connection-validate

	Validate a connection

SYNTAX
        opennms-tquadro:connection-validate alias

ARGUMENTS
        alias
                Alias
                (required)

DETAILS
        Validate an existing connection to a tquadro cmdb
----

[source, console]
.Delete an existing connection.
----
admin@opennms()> opennms-tquadro:connection-delete --help
DESCRIPTION
        opennms-tquadro:connection-delete

	Delete a connection

SYNTAX
        opennms-tquadro:connection-delete alias

ARGUMENTS
        alias
                Alias
                (required)

DETAILS
        Deletes a connection to a tquadro cmdb
----

== Examples

The following example adds a connection with the alias `theAlias` and assumes that the TQuadro CMDB is reachable by the URL `https://my.prism.net:9440/api/tquadro` .
```
admin@opennms()> opennms-tquadro:connection-add theAlias https://my.tquadro.net:9440/ TheUsername ThePassword
```
