= Requisitions
:imagesdir: ../assets/images

In order to monitor the status of an ip address into tquadro cmdb we need to associate to a node
tha category `TQuadroCmdb`. and a connection alias for showing the .
Only nodes with such a category will be checked whether they are asset into tquadro cmdb.

To identify the tquadro cmdb target to which the node should be checked against you have to associate a connection alias
to the node.

We suggest to create a requisition for a given connection alias.
Add to the requisition a policy for adding node metadata and set metadata.key='tquadro.alias' and metadata.value='connAlias'
Add to the requisition a policy for adding node category `TQuadroCmdb`.

The plugin provides a shell command to verify if an ip address is into tquadro cmdb

[source, console]
.Check Ip presence in Tquadro Cmdb.
----
admin@opennms()> opennms-tquadro:check --help
DESCRIPTION
        opennms-tquadro:check

	Check Asset TQuadro Cmdb

SYNTAX
        opennms-tquadro:check [options] alias ip

ARGUMENTS
        alias
                Connection Alias Identifing Remote TQuadro Cmdb
                (required)
        ip
               ip address for which verify prencence in CMDB
                (required)


OPTIONS
        --help
                Display this help message
DETAILS
        Check TQuadro if Ip is holded by Asset
----


