= Requisitions
:imagesdir: ../assets/images

In order to monitor the status of an ip address into tquadro cmdb we need to associate to a node
tha Service with Name `TQuadro`.
Only nodes with Ipaddress with bounded TQuadro will be checked whether they are listed as asset into tquadro cmdb.
To add the TQuadro Service to node ip Interface just add manually the Service to Node->Interface in Requisition.
Another option could be to set up a Detector (ICMP) to add the TQuadro Service to all Ip Interface provided or discovered.

To identify the tquadro cmdb target to which the node should be checked against you have to associate a connection alias
to the node, therefore we need to associate a connection alias for the TQuadro Cmdb Server. Set the meta-data tquadro.alias
in Context Node or Requisition to the proper value (The connection Alias should match a name of a TQuadro definied connection)

You can optionally create the Asset on Cmdb if it does not exist, setting the meta-data tquadro.create to true in Node or in Requisition Context
The plugin provides a shell command to verify if an ip address is into tquadro cmdb using the meta-data provided in Node or Requisition Context

To add the tquadro.alias meta-data in Context Node just set the proper valie editing the node into Requisition.
To add the tquadro.create meta-data in Context Node just set the value to true editing the node into Requisition.

In case we want to add tquadro.alias the meta-data in context Requisition
Add to the requisition a policy for adding node metadata and set metadata.key='tquadro.alias' and metadata.value='tqa'

In case we want to add tquadro.create the meta-data in context Requisition
Add to the requisition a policy for adding node metadata and set metadata.key='tquadro.create' and metadata.value='true'

[source, console]
.Check Ip presence in Tquadro Cmdb.
----
admin@opennms()> opennms-tquadro:check --help
DESCRIPTION
        opennms-tquadro:check

	Check Asset TQuadro Cmdb

SYNTAX
        opennms-tquadro:check [options] alias ip

ARGUMENTS
        alias
                Connection Alias Identifing Remote TQuadro Cmdb
                (required)
        ip
               ip address for which verify prencence in CMDB
                (required)


OPTIONS
        --help
                Display this help message
DETAILS
        Check TQuadro if Ip is holded by Asset
----


